// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl.proto

#ifndef PROTOBUF_ctrl_2eproto__INCLUDED
#define PROTOBUF_ctrl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace knapp {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ctrl_2eproto();
void protobuf_AssignDesc_ctrl_2eproto();
void protobuf_ShutdownFile_ctrl_2eproto();

class CtrlRequest;
class CtrlRequest_CreateVdevParam;
class CtrlRequest_MallocParam;
class CtrlRequest_PingParam;
class CtrlRequest_VdevRefParam;
class CtrlResponse;
class CtrlResponse_ResourceResponse;
class CtrlResponse_TextResponse;

enum CtrlRequest_Type {
  CtrlRequest_Type_PING = 0,
  CtrlRequest_Type_MALLOC = 1,
  CtrlRequest_Type_FREE = 2,
  CtrlRequest_Type_CREATE_VDEV = 3,
  CtrlRequest_Type_DESTROY_VDEV = 4
};
bool CtrlRequest_Type_IsValid(int value);
const CtrlRequest_Type CtrlRequest_Type_Type_MIN = CtrlRequest_Type_PING;
const CtrlRequest_Type CtrlRequest_Type_Type_MAX = CtrlRequest_Type_DESTROY_VDEV;
const int CtrlRequest_Type_Type_ARRAYSIZE = CtrlRequest_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* CtrlRequest_Type_descriptor();
inline const ::std::string& CtrlRequest_Type_Name(CtrlRequest_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    CtrlRequest_Type_descriptor(), value);
}
inline bool CtrlRequest_Type_Parse(
    const ::std::string& name, CtrlRequest_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CtrlRequest_Type>(
    CtrlRequest_Type_descriptor(), name, value);
}
enum CtrlResponse_Reply {
  CtrlResponse_Reply_SUCCESS = 0,
  CtrlResponse_Reply_FAILURE = 1
};
bool CtrlResponse_Reply_IsValid(int value);
const CtrlResponse_Reply CtrlResponse_Reply_Reply_MIN = CtrlResponse_Reply_SUCCESS;
const CtrlResponse_Reply CtrlResponse_Reply_Reply_MAX = CtrlResponse_Reply_FAILURE;
const int CtrlResponse_Reply_Reply_ARRAYSIZE = CtrlResponse_Reply_Reply_MAX + 1;

const ::google::protobuf::EnumDescriptor* CtrlResponse_Reply_descriptor();
inline const ::std::string& CtrlResponse_Reply_Name(CtrlResponse_Reply value) {
  return ::google::protobuf::internal::NameOfEnum(
    CtrlResponse_Reply_descriptor(), value);
}
inline bool CtrlResponse_Reply_Parse(
    const ::std::string& name, CtrlResponse_Reply* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CtrlResponse_Reply>(
    CtrlResponse_Reply_descriptor(), name, value);
}
// ===================================================================

class CtrlRequest_PingParam : public ::google::protobuf::Message {
 public:
  CtrlRequest_PingParam();
  virtual ~CtrlRequest_PingParam();

  CtrlRequest_PingParam(const CtrlRequest_PingParam& from);

  inline CtrlRequest_PingParam& operator=(const CtrlRequest_PingParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlRequest_PingParam& default_instance();

  void Swap(CtrlRequest_PingParam* other);

  // implements Message ----------------------------------------------

  inline CtrlRequest_PingParam* New() const { return New(NULL); }

  CtrlRequest_PingParam* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlRequest_PingParam& from);
  void MergeFrom(const CtrlRequest_PingParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlRequest_PingParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string msg = 1;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:knapp.CtrlRequest.PingParam)
 private:
  inline void set_has_msg();
  inline void clear_has_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlRequest_PingParam* default_instance_;
};
// -------------------------------------------------------------------

class CtrlRequest_MallocParam : public ::google::protobuf::Message {
 public:
  CtrlRequest_MallocParam();
  virtual ~CtrlRequest_MallocParam();

  CtrlRequest_MallocParam(const CtrlRequest_MallocParam& from);

  inline CtrlRequest_MallocParam& operator=(const CtrlRequest_MallocParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlRequest_MallocParam& default_instance();

  void Swap(CtrlRequest_MallocParam* other);

  // implements Message ----------------------------------------------

  inline CtrlRequest_MallocParam* New() const { return New(NULL); }

  CtrlRequest_MallocParam* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlRequest_MallocParam& from);
  void MergeFrom(const CtrlRequest_MallocParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlRequest_MallocParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 size = 1;
  bool has_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 1;
  ::google::protobuf::uint64 size() const;
  void set_size(::google::protobuf::uint64 value);

  // required uint64 align = 2;
  bool has_align() const;
  void clear_align();
  static const int kAlignFieldNumber = 2;
  ::google::protobuf::uint64 align() const;
  void set_align(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:knapp.CtrlRequest.MallocParam)
 private:
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_align();
  inline void clear_has_align();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 size_;
  ::google::protobuf::uint64 align_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlRequest_MallocParam* default_instance_;
};
// -------------------------------------------------------------------

class CtrlRequest_CreateVdevParam : public ::google::protobuf::Message {
 public:
  CtrlRequest_CreateVdevParam();
  virtual ~CtrlRequest_CreateVdevParam();

  CtrlRequest_CreateVdevParam(const CtrlRequest_CreateVdevParam& from);

  inline CtrlRequest_CreateVdevParam& operator=(const CtrlRequest_CreateVdevParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlRequest_CreateVdevParam& default_instance();

  void Swap(CtrlRequest_CreateVdevParam* other);

  // implements Message ----------------------------------------------

  inline CtrlRequest_CreateVdevParam* New() const { return New(NULL); }

  CtrlRequest_CreateVdevParam* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlRequest_CreateVdevParam& from);
  void MergeFrom(const CtrlRequest_CreateVdevParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlRequest_CreateVdevParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 num_pcores = 1;
  bool has_num_pcores() const;
  void clear_num_pcores();
  static const int kNumPcoresFieldNumber = 1;
  ::google::protobuf::uint32 num_pcores() const;
  void set_num_pcores(::google::protobuf::uint32 value);

  // required uint32 num_lcores_per_pcore = 2;
  bool has_num_lcores_per_pcore() const;
  void clear_num_lcores_per_pcore();
  static const int kNumLcoresPerPcoreFieldNumber = 2;
  ::google::protobuf::uint32 num_lcores_per_pcore() const;
  void set_num_lcores_per_pcore(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:knapp.CtrlRequest.CreateVdevParam)
 private:
  inline void set_has_num_pcores();
  inline void clear_has_num_pcores();
  inline void set_has_num_lcores_per_pcore();
  inline void clear_has_num_lcores_per_pcore();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 num_pcores_;
  ::google::protobuf::uint32 num_lcores_per_pcore_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlRequest_CreateVdevParam* default_instance_;
};
// -------------------------------------------------------------------

class CtrlRequest_VdevRefParam : public ::google::protobuf::Message {
 public:
  CtrlRequest_VdevRefParam();
  virtual ~CtrlRequest_VdevRefParam();

  CtrlRequest_VdevRefParam(const CtrlRequest_VdevRefParam& from);

  inline CtrlRequest_VdevRefParam& operator=(const CtrlRequest_VdevRefParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlRequest_VdevRefParam& default_instance();

  void Swap(CtrlRequest_VdevRefParam* other);

  // implements Message ----------------------------------------------

  inline CtrlRequest_VdevRefParam* New() const { return New(NULL); }

  CtrlRequest_VdevRefParam* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlRequest_VdevRefParam& from);
  void MergeFrom(const CtrlRequest_VdevRefParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlRequest_VdevRefParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 vdev_id = 1;
  bool has_vdev_id() const;
  void clear_vdev_id();
  static const int kVdevIdFieldNumber = 1;
  ::google::protobuf::uint64 vdev_id() const;
  void set_vdev_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:knapp.CtrlRequest.VdevRefParam)
 private:
  inline void set_has_vdev_id();
  inline void clear_has_vdev_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 vdev_id_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlRequest_VdevRefParam* default_instance_;
};
// -------------------------------------------------------------------

class CtrlRequest : public ::google::protobuf::Message {
 public:
  CtrlRequest();
  virtual ~CtrlRequest();

  CtrlRequest(const CtrlRequest& from);

  inline CtrlRequest& operator=(const CtrlRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlRequest& default_instance();

  void Swap(CtrlRequest* other);

  // implements Message ----------------------------------------------

  inline CtrlRequest* New() const { return New(NULL); }

  CtrlRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlRequest& from);
  void MergeFrom(const CtrlRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef CtrlRequest_PingParam PingParam;
  typedef CtrlRequest_MallocParam MallocParam;
  typedef CtrlRequest_CreateVdevParam CreateVdevParam;
  typedef CtrlRequest_VdevRefParam VdevRefParam;

  typedef CtrlRequest_Type Type;
  static const Type PING =
    CtrlRequest_Type_PING;
  static const Type MALLOC =
    CtrlRequest_Type_MALLOC;
  static const Type FREE =
    CtrlRequest_Type_FREE;
  static const Type CREATE_VDEV =
    CtrlRequest_Type_CREATE_VDEV;
  static const Type DESTROY_VDEV =
    CtrlRequest_Type_DESTROY_VDEV;
  static inline bool Type_IsValid(int value) {
    return CtrlRequest_Type_IsValid(value);
  }
  static const Type Type_MIN =
    CtrlRequest_Type_Type_MIN;
  static const Type Type_MAX =
    CtrlRequest_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    CtrlRequest_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return CtrlRequest_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return CtrlRequest_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return CtrlRequest_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .knapp.CtrlRequest.Type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::knapp::CtrlRequest_Type type() const;
  void set_type(::knapp::CtrlRequest_Type value);

  // optional .knapp.CtrlRequest.PingParam ping_param = 2;
  bool has_ping_param() const;
  void clear_ping_param();
  static const int kPingParamFieldNumber = 2;
  const ::knapp::CtrlRequest_PingParam& ping_param() const;
  ::knapp::CtrlRequest_PingParam* mutable_ping_param();
  ::knapp::CtrlRequest_PingParam* release_ping_param();
  void set_allocated_ping_param(::knapp::CtrlRequest_PingParam* ping_param);

  // optional .knapp.CtrlRequest.MallocParam malloc_param = 3;
  bool has_malloc_param() const;
  void clear_malloc_param();
  static const int kMallocParamFieldNumber = 3;
  const ::knapp::CtrlRequest_MallocParam& malloc_param() const;
  ::knapp::CtrlRequest_MallocParam* mutable_malloc_param();
  ::knapp::CtrlRequest_MallocParam* release_malloc_param();
  void set_allocated_malloc_param(::knapp::CtrlRequest_MallocParam* malloc_param);

  // optional .knapp.CtrlRequest.CreateVdevParam create_vdev_param = 4;
  bool has_create_vdev_param() const;
  void clear_create_vdev_param();
  static const int kCreateVdevParamFieldNumber = 4;
  const ::knapp::CtrlRequest_CreateVdevParam& create_vdev_param() const;
  ::knapp::CtrlRequest_CreateVdevParam* mutable_create_vdev_param();
  ::knapp::CtrlRequest_CreateVdevParam* release_create_vdev_param();
  void set_allocated_create_vdev_param(::knapp::CtrlRequest_CreateVdevParam* create_vdev_param);

  // optional .knapp.CtrlRequest.VdevRefParam vdev_ref = 5;
  bool has_vdev_ref() const;
  void clear_vdev_ref();
  static const int kVdevRefFieldNumber = 5;
  const ::knapp::CtrlRequest_VdevRefParam& vdev_ref() const;
  ::knapp::CtrlRequest_VdevRefParam* mutable_vdev_ref();
  ::knapp::CtrlRequest_VdevRefParam* release_vdev_ref();
  void set_allocated_vdev_ref(::knapp::CtrlRequest_VdevRefParam* vdev_ref);

  // @@protoc_insertion_point(class_scope:knapp.CtrlRequest)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_ping_param();
  inline void clear_has_ping_param();
  inline void set_has_malloc_param();
  inline void clear_has_malloc_param();
  inline void set_has_create_vdev_param();
  inline void clear_has_create_vdev_param();
  inline void set_has_vdev_ref();
  inline void clear_has_vdev_ref();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::knapp::CtrlRequest_PingParam* ping_param_;
  ::knapp::CtrlRequest_MallocParam* malloc_param_;
  ::knapp::CtrlRequest_CreateVdevParam* create_vdev_param_;
  ::knapp::CtrlRequest_VdevRefParam* vdev_ref_;
  int type_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlRequest* default_instance_;
};
// -------------------------------------------------------------------

class CtrlResponse_TextResponse : public ::google::protobuf::Message {
 public:
  CtrlResponse_TextResponse();
  virtual ~CtrlResponse_TextResponse();

  CtrlResponse_TextResponse(const CtrlResponse_TextResponse& from);

  inline CtrlResponse_TextResponse& operator=(const CtrlResponse_TextResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlResponse_TextResponse& default_instance();

  void Swap(CtrlResponse_TextResponse* other);

  // implements Message ----------------------------------------------

  inline CtrlResponse_TextResponse* New() const { return New(NULL); }

  CtrlResponse_TextResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlResponse_TextResponse& from);
  void MergeFrom(const CtrlResponse_TextResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlResponse_TextResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string msg = 1;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:knapp.CtrlResponse.TextResponse)
 private:
  inline void set_has_msg();
  inline void clear_has_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlResponse_TextResponse* default_instance_;
};
// -------------------------------------------------------------------

class CtrlResponse_ResourceResponse : public ::google::protobuf::Message {
 public:
  CtrlResponse_ResourceResponse();
  virtual ~CtrlResponse_ResourceResponse();

  CtrlResponse_ResourceResponse(const CtrlResponse_ResourceResponse& from);

  inline CtrlResponse_ResourceResponse& operator=(const CtrlResponse_ResourceResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlResponse_ResourceResponse& default_instance();

  void Swap(CtrlResponse_ResourceResponse* other);

  // implements Message ----------------------------------------------

  inline CtrlResponse_ResourceResponse* New() const { return New(NULL); }

  CtrlResponse_ResourceResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlResponse_ResourceResponse& from);
  void MergeFrom(const CtrlResponse_ResourceResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlResponse_ResourceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 handle = 1;
  bool has_handle() const;
  void clear_handle();
  static const int kHandleFieldNumber = 1;
  ::google::protobuf::uint64 handle() const;
  void set_handle(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:knapp.CtrlResponse.ResourceResponse)
 private:
  inline void set_has_handle();
  inline void clear_has_handle();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 handle_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlResponse_ResourceResponse* default_instance_;
};
// -------------------------------------------------------------------

class CtrlResponse : public ::google::protobuf::Message {
 public:
  CtrlResponse();
  virtual ~CtrlResponse();

  CtrlResponse(const CtrlResponse& from);

  inline CtrlResponse& operator=(const CtrlResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlResponse& default_instance();

  void Swap(CtrlResponse* other);

  // implements Message ----------------------------------------------

  inline CtrlResponse* New() const { return New(NULL); }

  CtrlResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlResponse& from);
  void MergeFrom(const CtrlResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef CtrlResponse_TextResponse TextResponse;
  typedef CtrlResponse_ResourceResponse ResourceResponse;

  typedef CtrlResponse_Reply Reply;
  static const Reply SUCCESS =
    CtrlResponse_Reply_SUCCESS;
  static const Reply FAILURE =
    CtrlResponse_Reply_FAILURE;
  static inline bool Reply_IsValid(int value) {
    return CtrlResponse_Reply_IsValid(value);
  }
  static const Reply Reply_MIN =
    CtrlResponse_Reply_Reply_MIN;
  static const Reply Reply_MAX =
    CtrlResponse_Reply_Reply_MAX;
  static const int Reply_ARRAYSIZE =
    CtrlResponse_Reply_Reply_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Reply_descriptor() {
    return CtrlResponse_Reply_descriptor();
  }
  static inline const ::std::string& Reply_Name(Reply value) {
    return CtrlResponse_Reply_Name(value);
  }
  static inline bool Reply_Parse(const ::std::string& name,
      Reply* value) {
    return CtrlResponse_Reply_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .knapp.CtrlResponse.Reply reply = 1;
  bool has_reply() const;
  void clear_reply();
  static const int kReplyFieldNumber = 1;
  ::knapp::CtrlResponse_Reply reply() const;
  void set_reply(::knapp::CtrlResponse_Reply value);

  // optional .knapp.CtrlResponse.TextResponse text = 2;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::knapp::CtrlResponse_TextResponse& text() const;
  ::knapp::CtrlResponse_TextResponse* mutable_text();
  ::knapp::CtrlResponse_TextResponse* release_text();
  void set_allocated_text(::knapp::CtrlResponse_TextResponse* text);

  // optional .knapp.CtrlResponse.ResourceResponse resource = 3;
  bool has_resource() const;
  void clear_resource();
  static const int kResourceFieldNumber = 3;
  const ::knapp::CtrlResponse_ResourceResponse& resource() const;
  ::knapp::CtrlResponse_ResourceResponse* mutable_resource();
  ::knapp::CtrlResponse_ResourceResponse* release_resource();
  void set_allocated_resource(::knapp::CtrlResponse_ResourceResponse* resource);

  // @@protoc_insertion_point(class_scope:knapp.CtrlResponse)
 private:
  inline void set_has_reply();
  inline void clear_has_reply();
  inline void set_has_text();
  inline void clear_has_text();
  inline void set_has_resource();
  inline void clear_has_resource();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::knapp::CtrlResponse_TextResponse* text_;
  ::knapp::CtrlResponse_ResourceResponse* resource_;
  int reply_;
  friend void  protobuf_AddDesc_ctrl_2eproto();
  friend void protobuf_AssignDesc_ctrl_2eproto();
  friend void protobuf_ShutdownFile_ctrl_2eproto();

  void InitAsDefaultInstance();
  static CtrlResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CtrlRequest_PingParam

// required string msg = 1;
inline bool CtrlRequest_PingParam::has_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlRequest_PingParam::set_has_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlRequest_PingParam::clear_has_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlRequest_PingParam::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& CtrlRequest_PingParam::msg() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.PingParam.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CtrlRequest_PingParam::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.PingParam.msg)
}
inline void CtrlRequest_PingParam::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:knapp.CtrlRequest.PingParam.msg)
}
inline void CtrlRequest_PingParam::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:knapp.CtrlRequest.PingParam.msg)
}
inline ::std::string* CtrlRequest_PingParam::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:knapp.CtrlRequest.PingParam.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CtrlRequest_PingParam::release_msg() {
  // @@protoc_insertion_point(field_release:knapp.CtrlRequest.PingParam.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CtrlRequest_PingParam::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlRequest.PingParam.msg)
}

// -------------------------------------------------------------------

// CtrlRequest_MallocParam

// required uint64 size = 1;
inline bool CtrlRequest_MallocParam::has_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlRequest_MallocParam::set_has_size() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlRequest_MallocParam::clear_has_size() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlRequest_MallocParam::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 CtrlRequest_MallocParam::size() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.MallocParam.size)
  return size_;
}
inline void CtrlRequest_MallocParam::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.MallocParam.size)
}

// required uint64 align = 2;
inline bool CtrlRequest_MallocParam::has_align() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlRequest_MallocParam::set_has_align() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlRequest_MallocParam::clear_has_align() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlRequest_MallocParam::clear_align() {
  align_ = GOOGLE_ULONGLONG(0);
  clear_has_align();
}
inline ::google::protobuf::uint64 CtrlRequest_MallocParam::align() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.MallocParam.align)
  return align_;
}
inline void CtrlRequest_MallocParam::set_align(::google::protobuf::uint64 value) {
  set_has_align();
  align_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.MallocParam.align)
}

// -------------------------------------------------------------------

// CtrlRequest_CreateVdevParam

// required uint32 num_pcores = 1;
inline bool CtrlRequest_CreateVdevParam::has_num_pcores() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlRequest_CreateVdevParam::set_has_num_pcores() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlRequest_CreateVdevParam::clear_has_num_pcores() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlRequest_CreateVdevParam::clear_num_pcores() {
  num_pcores_ = 0u;
  clear_has_num_pcores();
}
inline ::google::protobuf::uint32 CtrlRequest_CreateVdevParam::num_pcores() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.CreateVdevParam.num_pcores)
  return num_pcores_;
}
inline void CtrlRequest_CreateVdevParam::set_num_pcores(::google::protobuf::uint32 value) {
  set_has_num_pcores();
  num_pcores_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.CreateVdevParam.num_pcores)
}

// required uint32 num_lcores_per_pcore = 2;
inline bool CtrlRequest_CreateVdevParam::has_num_lcores_per_pcore() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlRequest_CreateVdevParam::set_has_num_lcores_per_pcore() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlRequest_CreateVdevParam::clear_has_num_lcores_per_pcore() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlRequest_CreateVdevParam::clear_num_lcores_per_pcore() {
  num_lcores_per_pcore_ = 0u;
  clear_has_num_lcores_per_pcore();
}
inline ::google::protobuf::uint32 CtrlRequest_CreateVdevParam::num_lcores_per_pcore() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.CreateVdevParam.num_lcores_per_pcore)
  return num_lcores_per_pcore_;
}
inline void CtrlRequest_CreateVdevParam::set_num_lcores_per_pcore(::google::protobuf::uint32 value) {
  set_has_num_lcores_per_pcore();
  num_lcores_per_pcore_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.CreateVdevParam.num_lcores_per_pcore)
}

// -------------------------------------------------------------------

// CtrlRequest_VdevRefParam

// required uint64 vdev_id = 1;
inline bool CtrlRequest_VdevRefParam::has_vdev_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlRequest_VdevRefParam::set_has_vdev_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlRequest_VdevRefParam::clear_has_vdev_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlRequest_VdevRefParam::clear_vdev_id() {
  vdev_id_ = GOOGLE_ULONGLONG(0);
  clear_has_vdev_id();
}
inline ::google::protobuf::uint64 CtrlRequest_VdevRefParam::vdev_id() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.VdevRefParam.vdev_id)
  return vdev_id_;
}
inline void CtrlRequest_VdevRefParam::set_vdev_id(::google::protobuf::uint64 value) {
  set_has_vdev_id();
  vdev_id_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.VdevRefParam.vdev_id)
}

// -------------------------------------------------------------------

// CtrlRequest

// required .knapp.CtrlRequest.Type type = 1;
inline bool CtrlRequest::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlRequest::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::knapp::CtrlRequest_Type CtrlRequest::type() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.type)
  return static_cast< ::knapp::CtrlRequest_Type >(type_);
}
inline void CtrlRequest::set_type(::knapp::CtrlRequest_Type value) {
  assert(::knapp::CtrlRequest_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlRequest.type)
}

// optional .knapp.CtrlRequest.PingParam ping_param = 2;
inline bool CtrlRequest::has_ping_param() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlRequest::set_has_ping_param() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlRequest::clear_has_ping_param() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlRequest::clear_ping_param() {
  if (ping_param_ != NULL) ping_param_->::knapp::CtrlRequest_PingParam::Clear();
  clear_has_ping_param();
}
inline const ::knapp::CtrlRequest_PingParam& CtrlRequest::ping_param() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.ping_param)
  return ping_param_ != NULL ? *ping_param_ : *default_instance_->ping_param_;
}
inline ::knapp::CtrlRequest_PingParam* CtrlRequest::mutable_ping_param() {
  set_has_ping_param();
  if (ping_param_ == NULL) {
    ping_param_ = new ::knapp::CtrlRequest_PingParam;
  }
  // @@protoc_insertion_point(field_mutable:knapp.CtrlRequest.ping_param)
  return ping_param_;
}
inline ::knapp::CtrlRequest_PingParam* CtrlRequest::release_ping_param() {
  // @@protoc_insertion_point(field_release:knapp.CtrlRequest.ping_param)
  clear_has_ping_param();
  ::knapp::CtrlRequest_PingParam* temp = ping_param_;
  ping_param_ = NULL;
  return temp;
}
inline void CtrlRequest::set_allocated_ping_param(::knapp::CtrlRequest_PingParam* ping_param) {
  delete ping_param_;
  ping_param_ = ping_param;
  if (ping_param) {
    set_has_ping_param();
  } else {
    clear_has_ping_param();
  }
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlRequest.ping_param)
}

// optional .knapp.CtrlRequest.MallocParam malloc_param = 3;
inline bool CtrlRequest::has_malloc_param() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CtrlRequest::set_has_malloc_param() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CtrlRequest::clear_has_malloc_param() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CtrlRequest::clear_malloc_param() {
  if (malloc_param_ != NULL) malloc_param_->::knapp::CtrlRequest_MallocParam::Clear();
  clear_has_malloc_param();
}
inline const ::knapp::CtrlRequest_MallocParam& CtrlRequest::malloc_param() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.malloc_param)
  return malloc_param_ != NULL ? *malloc_param_ : *default_instance_->malloc_param_;
}
inline ::knapp::CtrlRequest_MallocParam* CtrlRequest::mutable_malloc_param() {
  set_has_malloc_param();
  if (malloc_param_ == NULL) {
    malloc_param_ = new ::knapp::CtrlRequest_MallocParam;
  }
  // @@protoc_insertion_point(field_mutable:knapp.CtrlRequest.malloc_param)
  return malloc_param_;
}
inline ::knapp::CtrlRequest_MallocParam* CtrlRequest::release_malloc_param() {
  // @@protoc_insertion_point(field_release:knapp.CtrlRequest.malloc_param)
  clear_has_malloc_param();
  ::knapp::CtrlRequest_MallocParam* temp = malloc_param_;
  malloc_param_ = NULL;
  return temp;
}
inline void CtrlRequest::set_allocated_malloc_param(::knapp::CtrlRequest_MallocParam* malloc_param) {
  delete malloc_param_;
  malloc_param_ = malloc_param;
  if (malloc_param) {
    set_has_malloc_param();
  } else {
    clear_has_malloc_param();
  }
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlRequest.malloc_param)
}

// optional .knapp.CtrlRequest.CreateVdevParam create_vdev_param = 4;
inline bool CtrlRequest::has_create_vdev_param() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CtrlRequest::set_has_create_vdev_param() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CtrlRequest::clear_has_create_vdev_param() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CtrlRequest::clear_create_vdev_param() {
  if (create_vdev_param_ != NULL) create_vdev_param_->::knapp::CtrlRequest_CreateVdevParam::Clear();
  clear_has_create_vdev_param();
}
inline const ::knapp::CtrlRequest_CreateVdevParam& CtrlRequest::create_vdev_param() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.create_vdev_param)
  return create_vdev_param_ != NULL ? *create_vdev_param_ : *default_instance_->create_vdev_param_;
}
inline ::knapp::CtrlRequest_CreateVdevParam* CtrlRequest::mutable_create_vdev_param() {
  set_has_create_vdev_param();
  if (create_vdev_param_ == NULL) {
    create_vdev_param_ = new ::knapp::CtrlRequest_CreateVdevParam;
  }
  // @@protoc_insertion_point(field_mutable:knapp.CtrlRequest.create_vdev_param)
  return create_vdev_param_;
}
inline ::knapp::CtrlRequest_CreateVdevParam* CtrlRequest::release_create_vdev_param() {
  // @@protoc_insertion_point(field_release:knapp.CtrlRequest.create_vdev_param)
  clear_has_create_vdev_param();
  ::knapp::CtrlRequest_CreateVdevParam* temp = create_vdev_param_;
  create_vdev_param_ = NULL;
  return temp;
}
inline void CtrlRequest::set_allocated_create_vdev_param(::knapp::CtrlRequest_CreateVdevParam* create_vdev_param) {
  delete create_vdev_param_;
  create_vdev_param_ = create_vdev_param;
  if (create_vdev_param) {
    set_has_create_vdev_param();
  } else {
    clear_has_create_vdev_param();
  }
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlRequest.create_vdev_param)
}

// optional .knapp.CtrlRequest.VdevRefParam vdev_ref = 5;
inline bool CtrlRequest::has_vdev_ref() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CtrlRequest::set_has_vdev_ref() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CtrlRequest::clear_has_vdev_ref() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CtrlRequest::clear_vdev_ref() {
  if (vdev_ref_ != NULL) vdev_ref_->::knapp::CtrlRequest_VdevRefParam::Clear();
  clear_has_vdev_ref();
}
inline const ::knapp::CtrlRequest_VdevRefParam& CtrlRequest::vdev_ref() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlRequest.vdev_ref)
  return vdev_ref_ != NULL ? *vdev_ref_ : *default_instance_->vdev_ref_;
}
inline ::knapp::CtrlRequest_VdevRefParam* CtrlRequest::mutable_vdev_ref() {
  set_has_vdev_ref();
  if (vdev_ref_ == NULL) {
    vdev_ref_ = new ::knapp::CtrlRequest_VdevRefParam;
  }
  // @@protoc_insertion_point(field_mutable:knapp.CtrlRequest.vdev_ref)
  return vdev_ref_;
}
inline ::knapp::CtrlRequest_VdevRefParam* CtrlRequest::release_vdev_ref() {
  // @@protoc_insertion_point(field_release:knapp.CtrlRequest.vdev_ref)
  clear_has_vdev_ref();
  ::knapp::CtrlRequest_VdevRefParam* temp = vdev_ref_;
  vdev_ref_ = NULL;
  return temp;
}
inline void CtrlRequest::set_allocated_vdev_ref(::knapp::CtrlRequest_VdevRefParam* vdev_ref) {
  delete vdev_ref_;
  vdev_ref_ = vdev_ref;
  if (vdev_ref) {
    set_has_vdev_ref();
  } else {
    clear_has_vdev_ref();
  }
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlRequest.vdev_ref)
}

// -------------------------------------------------------------------

// CtrlResponse_TextResponse

// required string msg = 1;
inline bool CtrlResponse_TextResponse::has_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlResponse_TextResponse::set_has_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlResponse_TextResponse::clear_has_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlResponse_TextResponse::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& CtrlResponse_TextResponse::msg() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlResponse.TextResponse.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CtrlResponse_TextResponse::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:knapp.CtrlResponse.TextResponse.msg)
}
inline void CtrlResponse_TextResponse::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:knapp.CtrlResponse.TextResponse.msg)
}
inline void CtrlResponse_TextResponse::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:knapp.CtrlResponse.TextResponse.msg)
}
inline ::std::string* CtrlResponse_TextResponse::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:knapp.CtrlResponse.TextResponse.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CtrlResponse_TextResponse::release_msg() {
  // @@protoc_insertion_point(field_release:knapp.CtrlResponse.TextResponse.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CtrlResponse_TextResponse::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlResponse.TextResponse.msg)
}

// -------------------------------------------------------------------

// CtrlResponse_ResourceResponse

// required uint64 handle = 1;
inline bool CtrlResponse_ResourceResponse::has_handle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlResponse_ResourceResponse::set_has_handle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlResponse_ResourceResponse::clear_has_handle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlResponse_ResourceResponse::clear_handle() {
  handle_ = GOOGLE_ULONGLONG(0);
  clear_has_handle();
}
inline ::google::protobuf::uint64 CtrlResponse_ResourceResponse::handle() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlResponse.ResourceResponse.handle)
  return handle_;
}
inline void CtrlResponse_ResourceResponse::set_handle(::google::protobuf::uint64 value) {
  set_has_handle();
  handle_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlResponse.ResourceResponse.handle)
}

// -------------------------------------------------------------------

// CtrlResponse

// required .knapp.CtrlResponse.Reply reply = 1;
inline bool CtrlResponse::has_reply() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlResponse::set_has_reply() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlResponse::clear_has_reply() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlResponse::clear_reply() {
  reply_ = 0;
  clear_has_reply();
}
inline ::knapp::CtrlResponse_Reply CtrlResponse::reply() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlResponse.reply)
  return static_cast< ::knapp::CtrlResponse_Reply >(reply_);
}
inline void CtrlResponse::set_reply(::knapp::CtrlResponse_Reply value) {
  assert(::knapp::CtrlResponse_Reply_IsValid(value));
  set_has_reply();
  reply_ = value;
  // @@protoc_insertion_point(field_set:knapp.CtrlResponse.reply)
}

// optional .knapp.CtrlResponse.TextResponse text = 2;
inline bool CtrlResponse::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlResponse::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlResponse::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlResponse::clear_text() {
  if (text_ != NULL) text_->::knapp::CtrlResponse_TextResponse::Clear();
  clear_has_text();
}
inline const ::knapp::CtrlResponse_TextResponse& CtrlResponse::text() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlResponse.text)
  return text_ != NULL ? *text_ : *default_instance_->text_;
}
inline ::knapp::CtrlResponse_TextResponse* CtrlResponse::mutable_text() {
  set_has_text();
  if (text_ == NULL) {
    text_ = new ::knapp::CtrlResponse_TextResponse;
  }
  // @@protoc_insertion_point(field_mutable:knapp.CtrlResponse.text)
  return text_;
}
inline ::knapp::CtrlResponse_TextResponse* CtrlResponse::release_text() {
  // @@protoc_insertion_point(field_release:knapp.CtrlResponse.text)
  clear_has_text();
  ::knapp::CtrlResponse_TextResponse* temp = text_;
  text_ = NULL;
  return temp;
}
inline void CtrlResponse::set_allocated_text(::knapp::CtrlResponse_TextResponse* text) {
  delete text_;
  text_ = text;
  if (text) {
    set_has_text();
  } else {
    clear_has_text();
  }
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlResponse.text)
}

// optional .knapp.CtrlResponse.ResourceResponse resource = 3;
inline bool CtrlResponse::has_resource() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CtrlResponse::set_has_resource() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CtrlResponse::clear_has_resource() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CtrlResponse::clear_resource() {
  if (resource_ != NULL) resource_->::knapp::CtrlResponse_ResourceResponse::Clear();
  clear_has_resource();
}
inline const ::knapp::CtrlResponse_ResourceResponse& CtrlResponse::resource() const {
  // @@protoc_insertion_point(field_get:knapp.CtrlResponse.resource)
  return resource_ != NULL ? *resource_ : *default_instance_->resource_;
}
inline ::knapp::CtrlResponse_ResourceResponse* CtrlResponse::mutable_resource() {
  set_has_resource();
  if (resource_ == NULL) {
    resource_ = new ::knapp::CtrlResponse_ResourceResponse;
  }
  // @@protoc_insertion_point(field_mutable:knapp.CtrlResponse.resource)
  return resource_;
}
inline ::knapp::CtrlResponse_ResourceResponse* CtrlResponse::release_resource() {
  // @@protoc_insertion_point(field_release:knapp.CtrlResponse.resource)
  clear_has_resource();
  ::knapp::CtrlResponse_ResourceResponse* temp = resource_;
  resource_ = NULL;
  return temp;
}
inline void CtrlResponse::set_allocated_resource(::knapp::CtrlResponse_ResourceResponse* resource) {
  delete resource_;
  resource_ = resource;
  if (resource) {
    set_has_resource();
  } else {
    clear_has_resource();
  }
  // @@protoc_insertion_point(field_set_allocated:knapp.CtrlResponse.resource)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace knapp

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::knapp::CtrlRequest_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::knapp::CtrlRequest_Type>() {
  return ::knapp::CtrlRequest_Type_descriptor();
}
template <> struct is_proto_enum< ::knapp::CtrlResponse_Reply> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::knapp::CtrlResponse_Reply>() {
  return ::knapp::CtrlResponse_Reply_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ctrl_2eproto__INCLUDED
